//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Term
    {
        public int MOT_ID { get; set; }
        [Required]
        public string Headword { get; set; }
        [Required]
        public string Definition { get; set; }
        
        public string Full_form { get; set; }
        
        public string Abbreviations { get; set; }
        
        public string Synonyms { get; set; }
    }
}
